name: Check bundle size

on:
  push:
    branches: [main]
  pull_request:
    types: [synchronize, opened, reopened]

permissions: write-all

jobs:
  check-bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Paths filter
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'src/**'
              - 'angular.json'
              - 'tsconfig*.json'
              - 'package.json'
              - 'pnpm-lock.yaml'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setup PNPM
        if: steps.changes.outputs.app == 'true'
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        if: steps.changes.outputs.app == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        if: steps.changes.outputs.app == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build (no hashing for BundleMon)
        if: steps.changes.outputs.app == 'true'
        run: npx ng build --named-chunks=true --output-hashing=none --source-map=true

      - name: BundleMon
        if: steps.changes.outputs.app == 'true'
        uses: lironer/bundlemon-action@v1
